
services:
    app: 
        image: av-prod
        environment:
            - API_PORT=${API_PORT}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - ADMIN_EMAIL=${ADMIN_EMAIL}
            - MONGO_URL=${MONGO_URL}
            - JWT_SECRET=${JWT_SECRET}
            - SEEDER=${SEEDER}
        depends_on:
            - db
        ports:
            - "3000:3000"
    db:
        image: mongo:4.4.13